### ISSUE TITLE
funktioniert bei mir leider nicht

### ISSUE THREAD

**Issue by ezi00** [Woersty/LoxBerry-Plugin-DynDNS-Refresher#1]
hallo.

bei mir scheint es ein Problem zu geben
`[17-Sep-2017 10:05:02 Europe/Berlin] PHP Warning:  syntax error, unexpected '!' in /opt/loxberry/webfrontend/html/plugins/dyndns_refresher/../../../../config/system/general.cfg on line 44
 in /opt/loxberry/webfrontend/html/plugins/dyndns_refresher/index.php on line 55
2017-09-17 10:05:02 Error reading general config! [direct]`

ich verwende die loxberry version 0.2.3 und die 0.6 vom dyndns refresher.
Updaten will ich einen no-ip eintrag, der Link funktioniert im Browser.

In der Zeile 44 der general.cfg steht das passwort vom loxberry !?!?

**Comment by christianTF** [comment]
https://github.com/Woersty/LoxBerry-Plugin-DynDNS-Refresher/blob/master/webfrontend/html/index.php#L55

Ini-File:
`
pass=test!"§
`
PHP-Code:
`<?php
$myarray = parse_ini_file("test.cfg", FALSE, INI_SCANNER_RAW);
echo "First try: " . $myarray['pass'] . "\n";

$myarray = parse_ini_file("test.cfg");
echo "Second try: " . $myarray['pass'] . "\n";
?>`


Ergebnis:
First try: test!"§

PHP Warning:  syntax error, unexpected '!' in test.cfg on line 2
 in /home/christian/test.php on line 5
Second try:


--> parse_ini_file muss man im INI_SCANNER_RAW mode aufrufen, damit Sonderzeichen nicht geparst werden.

**Comment by christianTF** [comment]
@ezi00 Du solltest dir einen eigenen Loxone-Benutzer für den LoxBerry erstellen, der ein sicheres Passwort hat, aber keine Sonderzeichen (insbesondere keine Anführungszeichen, Prozent oder Rufzeichen).

**Comment by ezi00** [comment]
@christianTF danke für deine Hilfe!

Natürlich war es das Sonderzeichen im Passwort.
Wie empfohlen hab ich einen loxberry Benutzer im Miniserver angelegt, und siehe da, arbeitet perfekt
